### PR TITLE
added 'movie' parameter to make it work in Internet Explorer 8

### PR DESCRIPTION
**Pull request by vmovchan**
Hi, 
I've added few lines to make react-swf work in IE8.
Thank you for the library.

### CODE REVIEW

**Comment by syranide** [comment]
This was intentionally removed from the latest ReactSWF because React v15 no longer supports creating (flash-)objects in IE8. This is due to a bug in IE8 which instantiates objects as soon as they are created, not when they are inserted into the DOM, this means that it is instantiated before any params can be added and will thus always load blank.

So if you're required to support IE8 you need to instantiate your flash-object by constructing raw markup and using `dangerouslySetInnerHTML` instead which I feel is outside the scope of this module. Or sticking with React 0.14 and ReactSWF v.0.13.2.

**Comment by syranide** [comment]
PS. I may end up publishing such a module over the weekend, but it will not be compatible with this one.

**Comment by Vivanatomic** [comment]
Got it, thanks!
v0.13.2 works fine for me.

**Comment by syranide** [comment]
If you want to upgrade to React v15 and still support IE8-9 then I have now added `ReactSWFCompat`, you'll find more info in the readme.

**Comment by Vivanatomic** [comment]
it seems npm doesn't know about v1.0.3

**Comment by syranide** [comment]
I just updated in my own project so it should unless it just takes a bit of time to propagate...

**Comment by Vivanatomic** [comment]
ReactSWFCompat works fine, thanks again.

**Comment by syranide** [comment]
:+1:

**Pull request closed without merging**
